#!/bin/bash
#
# mongos     Startup script for the mongos server
#
# chkconfig: - 64 36
# description: Mongos Routing Server
#
# processname: mongos
#

# Source function library
. /etc/rc.d/init.d/functions

if [ -f /etc/sysconfig/mongos ]; then
        . /etc/sysconfig/mongos
fi

prog="mongos"
mongos="/usr/bin/mongos"
configdb="fire.rccc.ou.edu:27019"

RETVAL=0

start() {
        echo -n $"Starting $prog: "
        daemon --user mongod $mongos "--configdb $configdb --fork --logpath /var/log/mongodb/mongos.log --logappend 2>&1 >>/var/log/mongodb/mongos.log"
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && touch /var/lock/subsys/$prog
        return $RETVAL
}

stop() {
        echo -n $"Stopping $prog: "
        killproc $prog
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/$prog
        return $RETVAL
}

reload() {
        echo -n $"Reloading $prog: "
        killproc $prog -HUP
        RETVAL=$?
        echo
        return $RETVAL
}

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                stop
                start
                ;;
        condrestart)
                if [ -f /var/lock/subsys/$prog ]; then
                        stop
                        start
                fi
                ;;
        reload)
                reload
                ;;
        status)
                status $mongos
                RETVAL=$?
                ;;
        *)
                echo $"Usage: $0 {start|stop|restart|condrestart|reload|status}"
                RETVAL=1
esac

exit $RETVAL
